### ISSUE TITLE
No Calibration?  

### ISSUE THREAD

**Issue by ivbhatt** [RigacciOrg/py-qmc5883l#1]
You should add functionality for calibrating the device and functionality to adjust errors due to magnetic declination. 
I'll work on those and help you add them!
I believe this is the only QMC driver for the pi!

**Comment by RigacciOrg** [comment]
Please, give me hints about that, I'm studying the matter!
As a first try, I'm writing a Python script for simple calibration with MIN/MAX method (i.e. only on the XY plane). My goal is to have a console-only script based on curses, which will assist in the calibration procedure. It shows the rotation of the sensor and the number of acquired samples, once got a complete rotation and sufficient samples, it calculates the calibration coefficients.

**Comment by RigacciOrg** [comment]
I just added the **declination** property to adjust the **get_bearing()** value. Just set it after you istantiated the object, the value returned by get_bearing() will be adjusted. Call **get_bearing_raw()** to get the unadjusted value.

**Comment by ivbhatt** [comment]
Yeah. That should be enough. 
While using, user should simply do the get_bearing() for a few seconds/rotations and find MIN/MAX after that user could simply use some sort of mapping function.

**Comment by RigacciOrg** [comment]
For the moment the declination property is just to take into account the **magnetic declination** that you can get for your place using some web services (e.g. http://www.ngdc.noaa.gov/geomag-web/calculators/calculateDeclination). You can of course measure the actual declination of your device, to take into account any hard iron bias.
But for a true calibration to take into account sensor mis-alignment of X-Y axes (non-orthogonality) and sensor orientation bias, I'm working on an **ellipse fitting**. A simple program to acquire sample data and view the mis-alignment is almost ready...

**Comment by RigacciOrg** [comment]
With commit f3f5bebc3d5e2964256d2bb3d6517654957c0639 we have introduced the logic to apply a calibration matrix to the magnetic vector. Now we have two methods: **get_magnet_raw()** and **get_magnet()**. Likewise we have **get_bearing_raw()** and **get_bearing()**. The latter will automatically apply the **calibration** matrix and **declination** offset. Default values for calibration and declination are the identity matrix and zero (i.e. obtain the raw values).
I close the issue, please test!
